version: '3.3'
services:
  db:
    image: mysql:5.7
    environment: 
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: mydb
        MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
        volumes:
            — pgdatavol:/var/lib/mysql/data
        ports:
            — 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  tomcat:
    image: tomcat:9.0.13-jre11-slim
    volumes:
      - .:/code
    ports:
      - 8080:8080
    environment: 
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: mydb
        MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
        volumes:
            — pgdatavol:/var/lib/mysql/data
        ports:
            — 3306:3306
volumes:
    db_vol: 
